# Pulling a python image
FROM python:3.13-slim

WORKDIR /app

# Downloading used python libraries
COPY /Docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Testing that the dockerfile is accessing the actual project
CMD ["python", "testing/dockerTest.py"]