# Pulling a python image
FROM python:3.13-slim

WORKDIR /app

# Downloading used python libraries
COPY /Docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Runing the uvicorn service
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]